#Embedded file name: /Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/ableton/v2/base/__init__.py
from __future__ import absolute_import, print_function, unicode_literals
from .dependency import DependencyError, depends, inject
from .disconnectable import CompoundDisconnectable, Disconnectable, disconnectable
from .event import Event, EventError, EventObject, MultiSlot, ObservablePropertyAlias, SerializableListenableProperties, Slot, SlotGroup, has_event, listenable_property, listens, listens_group
from .gcutil import histogram, instances_by_name, refget
from .isclose import isclose
from .live_api_utils import duplicate_clip_loop, is_parameter_bipolar, liveobj_changed, liveobj_valid
from .proxy import Proxy, ProxyBase
from .abl_signal import Signal
from .util import Bindable, BooleanContext, NamedTuple, OutermostOnlyContext, PY2, PY3, Slicer, aggregate_contexts, chunks, clamp, compose, const, dict_diff, find_if, first, flatten, forward_property, get_slice, group, in_range, index_if, infinite_context_manager, instance_decorator, is_contextmanager, is_iterable, is_matrix, lazy_attribute, linear, maybe, memoize, mixin, monkeypatch, monkeypatch_extend, negate, next, nop, old_round, old_hasattr, overlaymap, print_message, product, recursive_map, remove_if, second, sign, slice_size, slicer, third, to_slice, trace_value, union
__all__ = (u'Bindable',
 u'BooleanContext',
 u'CompoundDisconnectable',
 u'DependencyError',
 u'Disconnectable',
 u'Event',
 u'EventError',
 u'EventObject',
 u'MultiSlot',
 u'NamedTuple',
 u'ObservablePropertyAlias',
 u'OutermostOnlyContext',
 u'Proxy',
 u'ProxyBase',
 u'PY2',
 u'PY3',
 u'SerializableListenableProperties',
 u'Signal',
 u'Slicer',
 u'Slot',
 u'SlotGroup',
 u'aggregate_contexts',
 u'chunks',
 u'clamp',
 u'compose',
 u'const',
 u'depends',
 u'dict_diff',
 u'disconnectable',
 u'duplicate_clip_loop',
 u'find_if',
 u'first',
 u'flatten',
 u'forward_property',
 u'get_slice',
 u'group',
 u'has_event',
 u'histogram',
 u'in_range',
 u'index_if',
 u'infinite_context_manager',
 u'inject',
 u'instance_decorator',
 u'instances_by_name',
 u'is_contextmanager',
 u'is_iterable',
 u'is_matrix',
 u'is_parameter_bipolar',
 u'isclose',
 u'lazy_attribute',
 u'linear',
 u'listenable_property',
 u'listens',
 u'listens_group',
 u'liveobj_changed',
 u'liveobj_valid',
 u'maybe',
 u'memoize',
 u'mixin',
 u'monkeypatch',
 u'monkeypatch_extend',
 u'negate',
 u'next',
 u'nop',
 u'overlaymap',
 u'old_round',
 u'old_hasattr',
 u'print_message',
 u'product',
 u'recursive_map',
 u'refget',
 u'remove_if',
 u'second',
 u'sign',
 u'slice_size',
 u'slicer',
 u'third',
 u'to_slice',
 u'trace_value',
 u'union')
