#Embedded file name: /Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/SL_MkIII/parameter_mapping_sensitivities.py
from __future__ import absolute_import, print_function, unicode_literals
from ableton.v2.base import liveobj_valid
from ableton.v2.control_surface import is_parameter_quantized
DEFAULT_SENSITIVITY_KEY = u'normal_sensitivity'
CONTINUOUS_MAPPING_SENSITIVITY = 1.0
QUANTIZED_MAPPING_SENSITIVITY = 0.2
PARAMETER_SENSITIVITIES = {u'UltraAnalog': {u'OSC1 Octave': {DEFAULT_SENSITIVITY_KEY: QUANTIZED_MAPPING_SENSITIVITY},
                  u'OSC2 Octave': {DEFAULT_SENSITIVITY_KEY: QUANTIZED_MAPPING_SENSITIVITY},
                  u'OSC1 Semi': {DEFAULT_SENSITIVITY_KEY: QUANTIZED_MAPPING_SENSITIVITY},
                  u'OSC1 Detune': {DEFAULT_SENSITIVITY_KEY: 0.5},
                  u'OSC2 Semi': {DEFAULT_SENSITIVITY_KEY: QUANTIZED_MAPPING_SENSITIVITY},
                  u'OSC2 Detune': {DEFAULT_SENSITIVITY_KEY: 0.5}},
 u'LoungeLizard': {u'Noise Pitch': {DEFAULT_SENSITIVITY_KEY: 0.5},
                   u'Damp Balance': {DEFAULT_SENSITIVITY_KEY: 0.5},
                   u'P Amp < Key': {DEFAULT_SENSITIVITY_KEY: 0.5},
                   u'Semitone': {DEFAULT_SENSITIVITY_KEY: 0.1},
                   u'Voices': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'Collision': {u'Res 1 Decay': {DEFAULT_SENSITIVITY_KEY: 0.5},
                u'LFO 1 Sync Rate': {DEFAULT_SENSITIVITY_KEY: QUANTIZED_MAPPING_SENSITIVITY},
                u'LFO 2 Sync Rate': {DEFAULT_SENSITIVITY_KEY: QUANTIZED_MAPPING_SENSITIVITY}},
 u'InstrumentImpulse': {u'1 Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5},
                        u'2 Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5},
                        u'3 Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5},
                        u'4 Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5},
                        u'5 Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5},
                        u'6 Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5},
                        u'7 Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5},
                        u'8 Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5}},
 u'OriginalSimpler': {u'Mode': {DEFAULT_SENSITIVITY_KEY: 0.001},
                      u'Playback': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'Start': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'End': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Sensitivity': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'S Start': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'S Length': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'S Loop Length': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Transpose': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'Detune': {DEFAULT_SENSITIVITY_KEY: 5.0},
                      u'Gain': {DEFAULT_SENSITIVITY_KEY: 0.1},
                      u'Env. Type': {DEFAULT_SENSITIVITY_KEY: 0.1},
                      u'Filter Freq': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'Filt < Vel': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'Filt < Key': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'Filt < LFO': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'LR < Key': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'Vol < LFO': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'Pan < RND': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'Pan < LFO': {DEFAULT_SENSITIVITY_KEY: 0.5},
                      u'L Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Warp Mode': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Preserve': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Envelope': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Grain Size Tones': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Grain Size Texture': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Flux': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Formants': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'Envelope Complex Pro': {DEFAULT_SENSITIVITY_KEY: 0.2},
                      u'L Retrig': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'Operator': {u'A Coarse': {DEFAULT_SENSITIVITY_KEY: 0.25},
               u'B Coarse': {DEFAULT_SENSITIVITY_KEY: 0.25},
               u'C Coarse': {DEFAULT_SENSITIVITY_KEY: 0.25},
               u'D Coarse': {DEFAULT_SENSITIVITY_KEY: 0.25},
               u'LFO Sync': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'MultiSampler': {u'O Coarse': {DEFAULT_SENSITIVITY_KEY: 0.25},
                   u'L 1 Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.25},
                   u'L 2 Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.25},
                   u'L 3 Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'StringStudio': {u'LFO SyncRate': {DEFAULT_SENSITIVITY_KEY: 0.2},
                   u'Octave': {DEFAULT_SENSITIVITY_KEY: 0.2},
                   u'Semitone': {DEFAULT_SENSITIVITY_KEY: 0.25},
                   u'Fine Tune': {DEFAULT_SENSITIVITY_KEY: 0.5}},
 u'MidiArpeggiator': {u'Style': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Synced Rate': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Offset': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Transp. Steps': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Transp. Dist.': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Repeats': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Ret. Interval': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Groove': {DEFAULT_SENSITIVITY_KEY: 0.25},
                      u'Retrigger Mode': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'MidiNoteLength': {u'Synced Length': {DEFAULT_SENSITIVITY_KEY: 0.1}},
 u'MidiPitcher': {u'Pitch': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'MidiRandom': {u'Choices': {DEFAULT_SENSITIVITY_KEY: 0.3},
                 u'Scale': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'MidiScale': {u'Base': {DEFAULT_SENSITIVITY_KEY: 0.2},
                u'Transpose': {DEFAULT_SENSITIVITY_KEY: 0.25},
                u'Range': {DEFAULT_SENSITIVITY_KEY: 0.1},
                u'Lowest': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'Amp': {u'Bass': {DEFAULT_SENSITIVITY_KEY: 0.5},
          u'Middle': {DEFAULT_SENSITIVITY_KEY: 0.5},
          u'Treble': {DEFAULT_SENSITIVITY_KEY: 0.5},
          u'Presence': {DEFAULT_SENSITIVITY_KEY: 0.5},
          u'Gain': {DEFAULT_SENSITIVITY_KEY: 0.5},
          u'Volume': {DEFAULT_SENSITIVITY_KEY: 0.5},
          u'Dry/Wet': {DEFAULT_SENSITIVITY_KEY: 0.5}},
 u'AutoFilter': {u'Frequency': {DEFAULT_SENSITIVITY_KEY: 1},
                 u'Env. Modulation': {DEFAULT_SENSITIVITY_KEY: 0.5},
                 u'LFO Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.1},
                 u'LFO Phase': {DEFAULT_SENSITIVITY_KEY: 0.5},
                 u'LFO Offset': {DEFAULT_SENSITIVITY_KEY: 0.5}},
 u'AutoPan': {u'Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.1}},
 u'BeatRepeat': {u'Grid': {DEFAULT_SENSITIVITY_KEY: 0.25},
                 u'Interval': {DEFAULT_SENSITIVITY_KEY: 0.25},
                 u'Offset': {DEFAULT_SENSITIVITY_KEY: 0.25},
                 u'Gate': {DEFAULT_SENSITIVITY_KEY: 0.25},
                 u'Pitch': {DEFAULT_SENSITIVITY_KEY: 0.25},
                 u'Variation': {DEFAULT_SENSITIVITY_KEY: 0.25},
                 u'Mix Type': {DEFAULT_SENSITIVITY_KEY: 0.25},
                 u'Grid': {DEFAULT_SENSITIVITY_KEY: 0.25},
                 u'Variation Type': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'Corpus': {u'LFO Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.1},
             u'Transpose': {DEFAULT_SENSITIVITY_KEY: 0.25},
             u'Fine': {DEFAULT_SENSITIVITY_KEY: 0.26}},
 u'Echo': {u'Mod Rate': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'Eq8': {u'Band': {DEFAULT_SENSITIVITY_KEY: 0.5},
          u'1 Frequency A': {DEFAULT_SENSITIVITY_KEY: 0.4},
          u'2 Frequency A': {DEFAULT_SENSITIVITY_KEY: 0.4},
          u'3 Frequency A': {DEFAULT_SENSITIVITY_KEY: 0.4},
          u'4 Frequency A': {DEFAULT_SENSITIVITY_KEY: 0.4},
          u'5 Frequency A': {DEFAULT_SENSITIVITY_KEY: 0.4},
          u'6 Frequency A': {DEFAULT_SENSITIVITY_KEY: 0.4},
          u'7 Frequency A': {DEFAULT_SENSITIVITY_KEY: 0.4},
          u'8 Frequency A': {DEFAULT_SENSITIVITY_KEY: 0.4}},
 u'Flanger': {u'Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.1}},
 u'FrequencyShifter': {u'Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'GrainDelay': {u'Pitch': {DEFAULT_SENSITIVITY_KEY: 0.1}},
 u'Phaser': {u'LFO Sync Rate': {DEFAULT_SENSITIVITY_KEY: 0.1}},
 u'Resonator': {u'II Pitch': {DEFAULT_SENSITIVITY_KEY: 0.25},
                u'III Pitch': {DEFAULT_SENSITIVITY_KEY: 0.25},
                u'IV Pitch': {DEFAULT_SENSITIVITY_KEY: 0.25},
                u'V Pitch': {DEFAULT_SENSITIVITY_KEY: 0.25}},
 u'InstrumentVector': {u'Osc 1 Pitch': {DEFAULT_SENSITIVITY_KEY: 5.0},
                       u'Osc 2 Pitch': {DEFAULT_SENSITIVITY_KEY: 5.0},
                       u'Osc 1 Category': {DEFAULT_SENSITIVITY_KEY: 0.5},
                       u'Osc 2 Category': {DEFAULT_SENSITIVITY_KEY: 0.5},
                       u'LFO 1 S. Rate': {DEFAULT_SENSITIVITY_KEY: 0.25},
                       u'LFO 2 S. Rate': {DEFAULT_SENSITIVITY_KEY: 0.25},
                       u'Unison Mode': {DEFAULT_SENSITIVITY_KEY: 0.5}}}

def sensitivity_mapping_for_parameter(parameter):
    is_quantized = is_parameter_quantized(parameter, parameter and parameter.canonical_parent)
    if is_quantized:
        return QUANTIZED_MAPPING_SENSITIVITY
    return CONTINUOUS_MAPPING_SENSITIVITY


def parameter_mapping_sensitivity(parameter, device_class = None):
    parameter_name = parameter.name if liveobj_valid(parameter) else u''
    try:
        return PARAMETER_SENSITIVITIES[device_class][parameter_name][DEFAULT_SENSITIVITY_KEY]
    except KeyError:
        return sensitivity_mapping_for_parameter(parameter)
