#Embedded file name: /Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/Push2/device_parameter_icons.py
from __future__ import absolute_import, print_function, unicode_literals
IMAGE_ID_TO_FILENAME = {u'amp_bass': (u'amp_bass.svg', u''),
 u'amp_blues': (u'amp_blues.svg', u''),
 u'amp_boost': (u'amp_boost.svg', u''),
 u'amp_clean': (u'amp_clean.svg', u''),
 u'amp_heavy': (u'amp_heavy.svg', u''),
 u'amp_lead': (u'amp_lead.svg', u''),
 u'amp_rock': (u'amp_rock.svg', u''),
 u'armed': (u'armed.svg', u''),
 u'cabinet_1x12': (u'cabinet_1x12.svg', u''),
 u'cabinet_2x12': (u'cabinet_2x12.svg', u''),
 u'cabinet_4x10': (u'cabinet_4x10.svg', u''),
 u'cabinet_4x10bass': (u'cabinet_4x10bass.svg', u''),
 u'cabinet_4x12': (u'cabinet_4x12.svg', u''),
 u'cancel_x': (u'cancel_x.svg', u''),
 u'circuit_clean': (u'circuit_clean.svg', u''),
 u'circuit_ms2': (u'circuit_ms2.svg', u''),
 u'circuit_osr': (u'circuit_osr.svg', u''),
 u'circuit_prd': (u'circuit_prd.svg', u''),
 u'circuit_smp': (u'circuit_smp.svg', u''),
 u'chorus_ensemble_classic': (u'chorus_ensemble_classic.svg', u''),
 u'chorus_ensemble_ensemble': (u'chorus_ensemble_ensemble.svg', u''),
 u'chorus_ensemble_vibrato': (u'chorus_ensemble_vibrato.svg', u''),
 u'co_beam': (u'co_beam.svg', u''),
 u'co_marimba': (u'co_marimba.svg', u''),
 u'co_membrane': (u'co_membrane.svg', u''),
 u'co_pipe': (u'co_pipe.svg', u''),
 u'co_plate': (u'co_plate.svg', u''),
 u'co_string': (u'co_string.svg', u''),
 u'co_tube': (u'co_tube.svg', u''),
 u'compressor_expand': (u'compressor_expand.svg', u''),
 u'compressor_peak': (u'compressor_peak.svg', u''),
 u'compressor_rms': (u'compressor_rms.svg', u''),
 u'control_off': (u'control_off.svg', u''),
 u'control_on': (u'control_on.svg', u''),
 u'delay_16th_1': (u'delay_16th_1.svg', u''),
 u'delay_16th_2': (u'delay_16th_2.svg', u''),
 u'delay_16th_3': (u'delay_16th_3.svg', u''),
 u'delay_16th_4': (u'delay_16th_4.svg', u''),
 u'delay_16th_5': (u'delay_16th_5.svg', u''),
 u'delay_16th_6': (u'delay_16th_6.svg', u''),
 u'delay_16th_8': (u'delay_16th_8.svg', u''),
 u'delay_16th_16': (u'delay_16th_16.svg', u''),
 u'delay_pingping_on': (u'delay_pingping_on.svg', u''),
 u'delay_pingping_off': (u'delay_pingping_off.svg', u''),
 u'device_pad': (u'device_pad.svg', u''),
 u'device_rack_drum': (u'device_rack_drum.svg', u''),
 u'device_rack_effect': (u'device_rack_effect.svg', u''),
 u'device_rack_instrument': (u'device_rack_instrument.svg', u''),
 u'drumbuss_soft': (u'drumbuss_soft.svg', u''),
 u'drumbuss_medium': (u'drumbuss_medium.svg', u''),
 u'drumbuss_hard': (u'drumbuss_hard.svg', u''),
 u'echo_16th': (u'echo_16th.svg', u''),
 u'echo_dotted': (u'echo_dotted.svg', u''),
 u'echo_note': (u'echo_note.svg', u''),
 u'echo_triplet': (u'echo_triplet.svg', u''),
 u'eq8_band1': (u'eq8_band1.svg', u''),
 u'eq8_band2': (u'eq8_band2.svg', u''),
 u'eq8_band3': (u'eq8_band3.svg', u''),
 u'eq8_band4': (u'eq8_band4.svg', u''),
 u'eq8_band5': (u'eq8_band5.svg', u''),
 u'eq8_band6': (u'eq8_band6.svg', u''),
 u'eq8_band7': (u'eq8_band7.svg', u''),
 u'eq8_band8': (u'eq8_band8.svg', u''),
 u'filter_band_12': (u'filter_band_12.svg', u'12BandPass_small.svg'),
 u'filter_band_24': (u'filter_band_24.svg', u'24BandPass_small.svg'),
 u'filter_band_6': (u'filter_band_6.svg', u''),
 u'filter_band_ladr': (u'filter_band_ladr.svg', u''),
 u'filter_band_ms2': (u'filter_band_ms2.svg', u''),
 u'filter_band_osr': (u'filter_band_osr.svg', u''),
 u'filter_band_prd': (u'filter_band_prd.svg', u''),
 u'filter_band_svf': (u'filter_band_svf.svg', u''),
 u'filter_bell': (u'filter_bell.svg', u'Bell_small.svg'),
 u'filter_formant_12': (u'filter_formant_12.svg', u''),
 u'filter_formant_6': (u'filter_formant_6.svg', u''),
 u'filter_high_12': (u'filter_high_12.svg', u'12HighPass_small.svg'),
 u'filter_high_24': (u'filter_high_24.svg', u'24HighPass_small.svg'),
 u'filter_high_48': (u'filter_high_48.svg', u'24HighPass_small.svg'),
 u'filter_high_ladr': (u'filter_high_ladr.svg', u''),
 u'filter_high_ms2': (u'filter_high_ms2.svg', u''),
 u'filter_high_osr': (u'filter_high_osr.svg', u''),
 u'filter_high_prd': (u'filter_high_prd.svg', u''),
 u'filter_high_shelf': (u'filter_high_shelf.svg', u'HighShelf_small.svg'),
 u'filter_high_svf': (u'filter_high_svf.svg', u''),
 u'filter_low_12': (u'filter_low_12.svg', u'12LowPass_small.svg'),
 u'filter_low_24': (u'filter_low_24.svg', u'24LowPass_small.svg'),
 u'filter_low_48': (u'filter_low_24.svg', u'24LowPass_small.svg'),
 u'filter_low_ladr': (u'filter_low_ladr.svg', u''),
 u'filter_low_ms2': (u'filter_low_ms2.svg', u''),
 u'filter_low_osr': (u'filter_low_osr.svg', u''),
 u'filter_low_prd': (u'filter_low_prd.svg', u''),
 u'filter_low_shelf': (u'filter_low_shelf.svg', u'LowShelf_small.svg'),
 u'filter_low_svf': (u'filter_low_svf.svg', u''),
 u'filter_morph_12': (u'filter_morph_12.svg', u'12Morph_small.svg'),
 u'filter_morph_24': (u'filter_morph_24.svg', u'24Morph_small.svg'),
 u'filter_notch_12': (u'filter_notch_12.svg', u'12Notch_small.svg'),
 u'filter_notch_24': (u'filter_notch_24.svg', u'24Notch_small.svg'),
 u'icon_horizontal1': (u'icon_horizontal1.svg', u''),
 u'icon_horizontal15': (u'icon_horizontal15.svg', u''),
 u'lfo_free': (u'lfo_free.svg', u''),
 u'lfo_phase': (u'lfo_phase.svg', u''),
 u'lfo_spin': (u'lfo_spin.svg', u''),
 u'lfo_sync': (u'lfo_sync.svg', u''),
 u'lfo_sine_small': (u'', u'lfo_sine_small.svg'),
 u'lfo_triangle_small': (u'', u'lfo_triangle_small.svg'),
 u'lfo_saw_up_small': (u'', u'lfo_saw_up_small.svg'),
 u'lfo_saw_down_small': (u'', u'lfo_saw_down_small.svg'),
 u'lfo_square_small': (u'', u'lfo_square_small.svg'),
 u'lfo_random_small': (u'', u'lfo_random_small.svg'),
 u'mic_condenser': (u'mic_condenser.svg', u''),
 u'mic_dynamic': (u'mic_dynamic.svg', u''),
 u'mic_far': (u'mic_far.svg', u''),
 u'mic_nearoff': (u'mic_nearoff.svg', u''),
 u'mic_nearon': (u'mic_nearon.svg', u''),
 u'osc_a': (u'osc_a.svg', u''),
 u'osc_alg_1': (u'osc_alg_1.svg', u''),
 u'osc_alg_10': (u'osc_alg_10.svg', u''),
 u'osc_alg_11': (u'osc_alg_11.svg', u''),
 u'osc_alg_2': (u'osc_alg_2.svg', u''),
 u'osc_alg_3': (u'osc_alg_3.svg', u''),
 u'osc_alg_4': (u'osc_alg_4.svg', u''),
 u'osc_alg_5': (u'osc_alg_5.svg', u''),
 u'osc_alg_6': (u'osc_alg_6.svg', u''),
 u'osc_alg_7': (u'osc_alg_7.svg', u''),
 u'osc_alg_8': (u'osc_alg_8.svg', u''),
 u'osc_alg_9': (u'osc_alg_9.svg', u''),
 u'osc_b': (u'osc_b.svg', u''),
 u'osc_c': (u'osc_c.svg', u''),
 u'osc_d': (u'osc_d.svg', u''),
 u'pedal_distortion': (u'pedal_distortion.svg', u''),
 u'pedal_fuzz': (u'pedal_fuzz.svg', u''),
 u'pedal_overdrive': (u'pedal_overdrive.svg', u''),
 u'phase_inverted': (u'phase_inverted.svg', u''),
 u'phase_normal': (u'phase_normal.svg', u''),
 u'route_in': (u'route_in.svg', u''),
 u'route_out': (u'route_out.svg', u''),
 u'simpler_1shot': (u'simpler_1shot.svg', u''),
 u'simpler_adsr': (u'simpler_adsr.svg', u''),
 u'simpler_slice': (u'simpler_slice.svg', u''),
 u'spectraltime_manual': (u'spectraltime_manual.svg', u''),
 u'spectraltime_retrigger': (u'spectraltime_retrigger.svg', u''),
 u'tension_bow': (u'tension_bow.svg', u''),
 u'tension_hammer': (u'tension_hammer.svg', u''),
 u'tension_hammerbounce': (u'tension_hammerbounce.svg', u''),
 u'tension_plectrum': (u'tension_plectrum.svg', u''),
 u'tension_plectum': (u'tension_plectum.svg', u''),
 u'track_group': (u'track_group.svg', u''),
 u'transmute_mod_mode_chorus': (u'transmute_chorus.svg', u''),
 u'transmute_mod_mode_granular': (u'transmute_granular.svg', u''),
 u'transmute_mod_mode_none': (u'transmute_none.svg', u''),
 u'transmute_mod_mode_wander': (u'transmute_wander.svg', u''),
 u'tube_a': (u'tube_a.svg', u''),
 u'utility_left': (u'utility_left.svg', u''),
 u'utility_right': (u'utility_right.svg', u''),
 u'utility_stereo': (u'utility_stereo.svg', u''),
 u'utility_swap': (u'utility_swap.svg', u''),
 u'tube_b': (u'tube_b.svg', u''),
 u'tube_c': (u'tube_c.svg', u''),
 u'voices_2': (u'voices_2.svg', u''),
 u'voices_3': (u'voices_3.svg', u''),
 u'voices_4': (u'voices_4.svg', u''),
 u'voices_5': (u'voices_5.svg', u''),
 u'voices_6': (u'voices_6.svg', u''),
 u'voices_7': (u'voices_7.svg', u''),
 u'voices_8': (u'voices_8.svg', u''),
 u'wave_noise_loop': (u'wave_noise_loop.svg', u''),
 u'wave_noise_white': (u'wave_noise_white.svg', u''),
 u'wave_saw_16': (u'wave_saw_16.svg', u''),
 u'wave_saw_3': (u'wave_saw_3.svg', u''),
 u'wave_saw_32': (u'wave_saw_32.svg', u''),
 u'wave_saw_4': (u'wave_saw_4.svg', u''),
 u'wave_saw_6': (u'wave_saw_6.svg', u''),
 u'wave_saw_64': (u'wave_saw_64.svg', u''),
 u'wave_saw_8': (u'wave_saw_8.svg', u''),
 u'wave_saw_down': (u'wave_saw_down.svg', u''),
 u'wave_saw_up': (u'wave_saw_up.svg', u''),
 u'wave_sh_mono': (u'wave_sh_mono.svg', u''),
 u'wave_sh_stereo': (u'wave_sh_stereo.svg', u''),
 u'wave_sine': (u'wave_sine.svg', u''),
 u'wave_sine_4bit': (u'wave_sine_4bit.svg', u''),
 u'wave_sine_8bit': (u'wave_sine_8bit.svg', u''),
 u'wave_square': (u'wave_square.svg', u''),
 u'wave_square_16': (u'wave_square_16.svg', u''),
 u'wave_square_3': (u'wave_square_3.svg', u''),
 u'wave_square_32': (u'wave_square_32.svg', u''),
 u'wave_square_4': (u'wave_square_4.svg', u''),
 u'wave_square_6': (u'wave_square_6.svg', u''),
 u'wave_square_64': (u'wave_square_64.svg', u''),
 u'wave_square_8': (u'wave_square_8.svg', u''),
 u'wave_triangle': (u'wave_triangle.svg', u''),
 u'wave_user': (u'wave_user.svg', u''),
 u'wavetable_effect_classic': (u'wavetable_effect_classic.svg', u''),
 u'wavetable_effect_fm': (u'wavetable_effect_fm.svg', u''),
 u'wavetable_effect_modern': (u'wavetable_effect_modern.svg', u''),
 u'wavetable_effect_none': (u'wavetable_effect_none.svg', u''),
 u'wavetable_env_loop': (u'wavetable_env_loop.svg', u''),
 u'wavetable_env_loop_none': (u'wavetable_env_loop_none.svg', u''),
 u'wavetable_env_loop_trigger': (u'wavetable_env_loop_trigger.svg', u''),
 u'wavetable_env_slope': (u'wavetable_env_slope.svg', u''),
 u'wavetable_env_time': (u'wavetable_env_time.svg', u''),
 u'wavetable_env_value': (u'wavetable_env_value.svg', u''),
 u'wavetable_filter_1': (u'', u'wavetable_filter_1_small.svg'),
 u'wavetable_filter_2': (u'', u'wavetable_filter_2_small.svg'),
 u'wavetable_filter_3': (u'', u'wavetable_filter_3_small.svg'),
 u'wavetable_filter_4': (u'', u'wavetable_filter_4_small.svg'),
 u'wavetable_filter_5': (u'', u'wavetable_filter_5_small.svg'),
 u'wavetable_filter_switch_1': (u'wavetable_filter_switch_1.svg', u''),
 u'wavetable_filter_switch_2': (u'wavetable_filter_switch_2.svg', u''),
 u'wavetable_octave_0': (u'wavetable_octave_0.svg', u''),
 u'wavetable_octave_minus_1': (u'wavetable_octave_minus_1.svg', u''),
 u'wavetable_octave_minus_2': (u'wavetable_octave_minus_2.svg', u''),
 u'wavetable_osc_1': (u'wavetable_osc_1.svg', u''),
 u'wavetable_osc_2': (u'wavetable_osc_2.svg', u''),
 u'wavetable_osc_mix': (u'wavetable_osc_mix.svg', u''),
 u'wavetable_osc_sub': (u'wavetable_osc_sub.svg', u''),
 u'wavetable_routing_parallel': (u'wavetable_routing_parallel.svg', u''),
 u'wavetable_routing_serial': (u'wavetable_routing_serial.svg', u''),
 u'wavetable_routing_split': (u'wavetable_routing_split.svg', u''),
 u'wavetable_unison_classic': (u'wavetable_unison_classic.svg', u''),
 u'wavetable_unison_shimmer': (u'wavetable_unison_shimmer.svg', u''),
 u'wavetable_unison_noise': (u'wavetable_unison_noise.svg', u''),
 u'wavetable_unison_none': (u'wavetable_unison_none.svg', u''),
 u'wavetable_unison_phase_sync': (u'wavetable_unison_phase_sync.svg', u''),
 u'wavetable_unison_position_spread': (u'wavetable_unison_position_spread.svg', u''),
 u'wavetable_unison_random': (u'wavetable_unison_random.svg', u''),
 u'workflow_clip': (u'workflow_clip.svg', u''),
 u'workflow_scene': (u'workflow_scene.svg', u''),
 u'hybrid_reverb_section_convolution': (u'hybrid_reverb_section_convolution.svg', u''),
 u'hybrid_reverb_section_algo': (u'hybrid_reverb_section_algo.svg', u''),
 u'hybrid_reverb_section_mix': (u'hybrid_reverb_section_mix.svg', u''),
 u'hybrid_reverb_section_eq': (u'hybrid_reverb_section_eq.svg', u''),
 u'hybrid_reverb_type_darkhall': (u'hybrid_reverb_type_darkhall.svg', u''),
 u'hybrid_reverb_type_shimmer': (u'hybrid_reverb_type_shimmer.svg', u''),
 u'hybrid_reverb_type_tides': (u'hybrid_reverb_type_tides.svg', u''),
 u'hybrid_reverb_type_quartz': (u'hybrid_reverb_type_quartz.svg', u''),
 u'hybrid_reverb_type_prism': (u'hybrid_reverb_type_prism.svg', u''),
 u'hybrid_reverb_vintage_1': (u'hybrid_reverb_vintage_1.svg', u''),
 u'hybrid_reverb_vintage_2': (u'hybrid_reverb_vintage_2.svg', u''),
 u'hybrid_reverb_vintage_3': (u'hybrid_reverb_vintage_3.svg', u''),
 u'hybrid_reverb_vintage_4': (u'hybrid_reverb_vintage_4.svg', u''),
 u'hybrid_reverb_vintage_5': (u'hybrid_reverb_vintage_5.svg', u''),
 u'hybrid_reverb_routing_serial': (u'hybrid_route_serial_eqoff.svg', u''),
 u'hybrid_reverb_routing_parallel': (u'hybrid_route_parallel_eqoff.svg', u''),
 u'hybrid_reverb_routing_convo': (u'hybrid_route_convo_eqoff.svg', u''),
 u'hybrid_reverb_routing_algo': (u'hybrid_route_algo_eqoff.svg', u''),
 u'hybrid_reverb_routing_serial_eq': (u'hybrid_route_serial_eqon_paoff.svg', u''),
 u'hybrid_reverb_routing_parallel_eq': (u'hybrid_route_parallel_eqon_paoff.svg', u''),
 u'hybrid_reverb_routing_convo_eq': (u'hybrid_route_convo_eqon.svg', u''),
 u'hybrid_reverb_routing_algo_eq': (u'hybrid_route_algo_eqon_paoff.svg', u''),
 u'hybrid_reverb_routing_serial_eq_pre_algo': (u'hybrid_route_serial_eqon_paon.svg', u''),
 u'hybrid_reverb_routing_parallel_eq_pre_algo': (u'hybrid_route_parallel_eqon_paon.svg', u''),
 u'hybrid_reverb_routing_convo_eq_pre_algo': (u'hybrid_route_convo_eqon.svg', u''),
 u'hybrid_reverb_routing_algo_eq_pre_algo': (u'hybrid_route_algo_eqon_paon.svg', u'')}
OPERATOR_OSCILLATORS = (u'wave_sine', u'wave_sine_4bit', u'wave_sine_8bit', u'wave_saw_3', u'wave_saw_4', u'wave_saw_6', u'wave_saw_8', u'wave_saw_16', u'wave_saw_32', u'wave_saw_64', u'wave_saw_down', u'wave_square_3', u'wave_square_4', u'wave_square_6', u'wave_square_8', u'wave_square_16', u'wave_square_32', u'wave_square_64', u'wave_square', u'wave_triangle', u'wave_noise_loop', u'wave_noise_white', u'wave_user')
ACTIVATE = (u'control_off', u'control_on')
ANALOG_OSCILLATORS = (u'wave_sine', u'wave_saw_down', u'wave_square', u'wave_noise_white')
ANALOG_L_F_O = (u'wave_sine', u'wave_triangle', u'wave_square', u'wave_noise_white', u'wave_noise_white')
ANALOG_FILTERS = (u'filter_low_12', u'filter_low_24', u'filter_band_6', u'filter_band_12', u'filter_notch_12', u'filter_notch_24', u'filter_high_12', u'filter_high_24', u'filter_formant_6', u'filter_formant_12')
RESONANCE_TYPES = (u'co_beam', u'co_marimba', u'co_string', u'co_membrane', u'co_plate', u'co_pipe', u'co_tube')
COLLISION_FILTERS = (u'filter_low_12', u'filter_high_12', u'filter_band_12', u'filter_band_6')
COLLISION_L_F_O = (u'wave_sine', u'wave_square', u'wave_triangle', u'wave_saw_up', u'wave_saw_down', u'wave_sh_mono', u'wave_noise_white')
IMPULSE_FILTERS = (u'filter_low_12', u'filter_low_24', u'filter_band_12', u'filter_band_24', u'filter_high_12', u'filter_high_24', u'filter_notch_12')
SAMPLER_OSCILLATORS = (u'wave_sine', u'wave_square', u'wave_triangle', u'wave_saw_up', u'wave_saw_down', u'wave_sh_mono')
LFO_WAVEFORMS = (u'wave_sine', u'wave_square', u'wave_triangle', u'wave_saw_up', u'wave_saw_down', u'wave_sh_stereo', u'wave_sh_mono')
STEREO_MODE = (u'lfo_phase', u'lfo_spin')
SYNC = (u'lfo_free', u'lfo_sync')
EQ8_FILTER_TYPES = (u'filter_high_48', u'filter_high_12', u'filter_low_shelf', u'filter_bell', u'filter_notch_24', u'filter_high_shelf', u'filter_low_12', u'filter_low_48')
CYTOMIC_FILTER_TYPES = (u'filter_low_48', u'filter_high_48', u'filter_band_24', u'filter_notch_24', u'filter_morph_24')
FILTER_CIRCUIT_TYPES = (u'circuit_clean', u'circuit_osr', u'circuit_ms2', u'circuit_smp', u'circuit_prd')
COMPRESSOR_MODES = (u'compressor_peak', u'compressor_rms', u'compressor_expand')
WAVETABLE_LOOP_MODE = (u'wavetable_env_loop_none', u'wavetable_env_loop_trigger', u'wavetable_env_loop')
WAVETABLE_OSCILLATOR_SWITCH = (u'wavetable_osc_1', u'wavetable_osc_2', u'wavetable_osc_sub', u'wavetable_osc_mix')
WAVETABLE_OSCILLATOR_EFFECT_TYPES = (u'wavetable_effect_none', u'wavetable_effect_fm', u'wavetable_effect_classic', u'wavetable_effect_modern')
WAVETABLE_FILTER_TYPES = (u'wavetable_filter_1', u'wavetable_filter_2', u'wavetable_filter_3', u'wavetable_filter_4', u'wavetable_filter_5')
WAVETABLE_LFO_TYPES = (u'lfo_sine_small', u'lfo_triangle_small', u'lfo_saw_down_small', u'lfo_square_small', u'lfo_random_small')
WAVETABLE_VOICES = (u'voices_2', u'voices_3', u'voices_4', u'voices_5', u'voices_6', u'voices_7', u'voices_8')
GENERIC_PARAMETER_IMAGES = {u'LFO Waveform': LFO_WAVEFORMS,
 u'Waveform': (u'wave_sine', u'wave_triangle', u'wave_saw_down', u'wave_sh_stereo'),
 u'Filter Type': (u'filter_low_48', u'filter_high_48', u'filter_band_24', u'filter_notch_24'),
 u'Ext. In On': ACTIVATE,
 u'LFO Sync': SYNC,
 u'Sync': SYNC,
 u'Adaptive Q': ACTIVATE,
 u'LFO Stereo Mode': STEREO_MODE,
 u'Side Listen': ACTIVATE,
 u'EQ On': ACTIVATE,
 u'EQ Mode': (u'filter_low_shelf', u'filter_bell', u'filter_high_shelf', u'filter_low_48', u'filter_band_24', u'filter_high_48')}
DEVICE_PARAMETER_IMAGES = {u'UltraAnalog': {u'OSC1 On/Off': ACTIVATE,
                  u'OSC2 On/Off': ACTIVATE,
                  u'F1 On/Off': ACTIVATE,
                  u'F2 On/Off': ACTIVATE,
                  u'AMP1 On/Off': ACTIVATE,
                  u'AMP2 On/Off': ACTIVATE,
                  u'Noise On/Off': ACTIVATE,
                  u'Unison On/Off': ACTIVATE,
                  u'Glide On/Off': ACTIVATE,
                  u'Glide Legato': ACTIVATE,
                  u'LFO1 On/Off': ACTIVATE,
                  u'LFO1 Sync': SYNC,
                  u'LFO2 On/Off': ACTIVATE,
                  u'LFO2 Sync': SYNC,
                  u'F1 On/Off': ACTIVATE,
                  u'F2 On/Off': ACTIVATE,
                  u'Vib On/Off': ACTIVATE,
                  u'OSC1 Shape': ANALOG_OSCILLATORS,
                  u'OSC2 Shape': ANALOG_OSCILLATORS,
                  u'F1 Type': ANALOG_FILTERS,
                  u'F2 Type': ANALOG_FILTERS,
                  u'LFO1 Shape': ANALOG_L_F_O,
                  u'LFO2 Shape': ANALOG_L_F_O},
 u'ChannelEq': {u'Highpass On': ACTIVATE},
 u'Collision': {u'Res 1 Type': RESONANCE_TYPES,
                u'Res 2 Type': RESONANCE_TYPES,
                u'Mallet On/Off': ACTIVATE,
                u'Noise On/Off': ACTIVATE,
                u'Res 1 On/Off': ACTIVATE,
                u'Res 2 On/Off': ACTIVATE,
                u'LFO 1 On/Off': ACTIVATE,
                u'LFO 2 On/Off': ACTIVATE,
                u'Mallet On/Off': ACTIVATE,
                u'Noise Filter Type': COLLISION_FILTERS,
                u'LFO 1 Shape': COLLISION_L_F_O,
                u'LFO 2 Shape': COLLISION_L_F_O,
                u'LFO 1 Sync': SYNC,
                u'LFO 2 Sync': SYNC},
 u'InstrumentImpulse': {u'1 Filter Type': IMPULSE_FILTERS,
                        u'2 Filter Type': IMPULSE_FILTERS,
                        u'3 Filter Type': IMPULSE_FILTERS,
                        u'4 Filter Type': IMPULSE_FILTERS,
                        u'5 Filter Type': IMPULSE_FILTERS,
                        u'6 Filter Type': IMPULSE_FILTERS,
                        u'7 Filter Type': IMPULSE_FILTERS,
                        u'8 Filter Type': IMPULSE_FILTERS},
 u'StringStudio': {u'Excitator Type': (u'tension_bow', u'tension_hammer', u'tension_hammerbounce', u'tension_plectrum'),
                   u'Filter Type': (u'filter_low_12', u'filter_low_24', u'filter_band_6', u'filter_band_12', u'filter_notch_12', u'filter_notch_24', u'filter_high_12', u'filter_high_24', u'filter_formant_6', u'filter_formant_12'),
                   u'Exc On/Off': ACTIVATE,
                   u'E Pos Abs': ACTIVATE,
                   u'Pickup On/Off': ACTIVATE,
                   u'Damper On': ACTIVATE,
                   u'Damper Gated': ACTIVATE,
                   u'D Pos Abs': ACTIVATE,
                   u'Term On/Off': ACTIVATE,
                   u'Body On/Off': ACTIVATE,
                   u'Filter On/Off': ACTIVATE,
                   u'LFO On/Off': ACTIVATE,
                   u'Vibrato On/Off': ACTIVATE,
                   u'Unison On/Off': ACTIVATE,
                   u'Porta On/Off': ACTIVATE,
                   u'Porta Legato': ACTIVATE,
                   u'Porta Prop': ACTIVATE,
                   u'FEG On/Off': ACTIVATE,
                   u'Damper Gated': ACTIVATE,
                   u'LFO Sync On': SYNC,
                   u'LFO Shape': (u'wave_sine', u'wave_triangle', u'wave_square', u'wave_sh_mono', u'wave_noise_white')},
 u'Operator': {u'Oscillator': (u'osc_a', u'osc_b', u'osc_c', u'osc_d'),
               u'Algorithm': (u'osc_alg_1', u'osc_alg_2', u'osc_alg_3', u'osc_alg_4', u'osc_alg_5', u'osc_alg_6', u'osc_alg_7', u'osc_alg_8', u'osc_alg_9', u'osc_alg_10', u'osc_alg_11'),
               u'Filter Type': CYTOMIC_FILTER_TYPES,
               u'Filter Circuit - LP/HP': FILTER_CIRCUIT_TYPES,
               u'Filter Circuit - BP/NO/Morph': FILTER_CIRCUIT_TYPES,
               u'LFO Type': (u'wave_sine', u'wave_square', u'wave_triangle', u'wave_saw_up', u'wave_saw_down', u'wave_sh_mono', u'wave_noise_white'),
               u'Osc-A Wave': OPERATOR_OSCILLATORS,
               u'Osc-B Wave': OPERATOR_OSCILLATORS,
               u'Osc-C Wave': OPERATOR_OSCILLATORS,
               u'Osc-D Wave': OPERATOR_OSCILLATORS,
               u'Filter On': ACTIVATE,
               u'Osc-A On': ACTIVATE,
               u'A Quantize': ACTIVATE,
               u'B Quantize': ACTIVATE,
               u'C Quantize': ACTIVATE,
               u'D Quantize': ACTIVATE,
               u'Osc-A Retrig': ACTIVATE,
               u'A Fix On ': ACTIVATE,
               u'Osc-B On': ACTIVATE,
               u'Osc-B Quantize': ACTIVATE,
               u'Osc-B Retrig': ACTIVATE,
               u'B Fix On ': ACTIVATE,
               u'Osc-C On': ACTIVATE,
               u'Osc-C Quantize': ACTIVATE,
               u'Osc-C Retrig': ACTIVATE,
               u'C Fix On ': ACTIVATE,
               u'Osc-D On': ACTIVATE,
               u'Osc-D Quantize': ACTIVATE,
               u'Osc-D Retrig': ACTIVATE,
               u'D Fix On ': ACTIVATE,
               u'LFO On': ACTIVATE,
               u'LFO Retrigger': ACTIVATE,
               u'Glide On': ACTIVATE,
               u'Pe On': ACTIVATE,
               u'LFO < Pe': ACTIVATE,
               u'Osc-A < Pe': ACTIVATE,
               u'Osc-B < Pe': ACTIVATE,
               u'Osc-C < Pe': ACTIVATE,
               u'Osc-D < Pe': ACTIVATE,
               u'Filt < LFO': ACTIVATE,
               u'Osc-A < LFO': ACTIVATE,
               u'Osc-B < LFO': ACTIVATE,
               u'Osc-C < LFO': ACTIVATE,
               u'Osc-D < LFO': ACTIVATE},
 u'MultiSampler': {u'F On': ACTIVATE,
                   u'Fe On': ACTIVATE,
                   u'Shaper On': ACTIVATE,
                   u'Osc On': ACTIVATE,
                   u'O Fix On': ACTIVATE,
                   u'O Type': OPERATOR_OSCILLATORS,
                   u'Pe On': ACTIVATE,
                   u'L 1 On': ACTIVATE,
                   u'L 1 Sync': SYNC,
                   u'L 1 Retrig': ACTIVATE,
                   u'L 1 Wave': SAMPLER_OSCILLATORS,
                   u'L 2 On': ACTIVATE,
                   u'L 2 Sync': SYNC,
                   u'L 2 St Mode': STEREO_MODE,
                   u'L 2 Retrig': ACTIVATE,
                   u'L 2 Wave': SAMPLER_OSCILLATORS,
                   u'L 3 On': ACTIVATE,
                   u'L 3 Sync': SYNC,
                   u'L 3 St Mode': STEREO_MODE,
                   u'L 3 Retrig': ACTIVATE,
                   u'L 3 Wave': SAMPLER_OSCILLATORS,
                   u'Ae On': ACTIVATE,
                   u'Filter Type': CYTOMIC_FILTER_TYPES,
                   u'Filter Circuit - LP/HP': FILTER_CIRCUIT_TYPES,
                   u'Filter Circuit - BP/NO/Morph': FILTER_CIRCUIT_TYPES},
 u'OriginalSimpler': {u'F On': ACTIVATE,
                      u'Fe On': ACTIVATE,
                      u'L On': ACTIVATE,
                      u'L Retrig': ACTIVATE,
                      u'Pe On': ACTIVATE,
                      u'L Wave': (u'wave_sine', u'wave_square', u'wave_triangle', u'wave_saw_down', u'wave_saw_up', u'wave_sh_mono'),
                      u'Filter Type': CYTOMIC_FILTER_TYPES,
                      u'Filter Circuit - LP/HP': FILTER_CIRCUIT_TYPES,
                      u'Filter Circuit - BP/NO/Morph': FILTER_CIRCUIT_TYPES},
 u'Amp': {u'Amp Type': (u'amp_clean', u'amp_boost', u'amp_blues', u'amp_rock', u'amp_lead', u'amp_heavy', u'amp_bass'),
          u'Dual Mono': ACTIVATE},
 u'AutoFilter': {u'LFO Quantize On': ACTIVATE,
                 u'Filter Type': CYTOMIC_FILTER_TYPES,
                 u'Filter Circuit - LP/HP': FILTER_CIRCUIT_TYPES,
                 u'Filter Circuit - BP/NO/Morph': FILTER_CIRCUIT_TYPES},
 u'AutoPan': {u'Invert': (u'phase_normal', u'phase_inverted'),
              u'LFO Type': SYNC,
              u'Stereo Mode': STEREO_MODE},
 u'BeatRepeat': {u'Filter On': ACTIVATE,
                 u'Repeat': ACTIVATE,
                 u'Block Triplets': ACTIVATE},
 u'Cabinet': {u'Dual Mono': ACTIVATE,
              u'Cabinet Type': (u'cabinet_1x12', u'cabinet_2x12', u'cabinet_4x12', u'cabinet_4x10', u'cabinet_4x10bass'),
              u'Microphone Type': (u'mic_condenser', u'mic_dynamic'),
              u'Microphone Position': (u'mic_nearon', u'mic_nearoff', u'mic_far')},
 u'Chorus': {u'LFO Extend On': ACTIVATE,
             u'Link On': ACTIVATE},
 u'Chorus2': {u'Mode': (u'chorus_ensemble_classic', u'chorus_ensemble_ensemble', u'chorus_ensemble_vibrato')},
 u'Compressor2': {u'Auto Release On/Off': ACTIVATE,
                  u'Makeup': ACTIVATE,
                  u'Model': COMPRESSOR_MODES},
 u'Corpus': {u'Resonance Type': RESONANCE_TYPES,
             u'LFO On/Off': ACTIVATE,
             u'LFO Shape': (u'wave_sine', u'wave_square', u'wave_triangle', u'wave_saw_up', u'wave_saw_down', u'wave_sh_mono', u'wave_noise_white'),
             u'LFO Stereo Mode': STEREO_MODE,
             u'MIDI Frequency': ACTIVATE,
             u'Note Off': ACTIVATE,
             u'Filter On/Off': ACTIVATE},
 u'Delay': {u'L 16th': (u'delay_16th_1', u'delay_16th_2', u'delay_16th_3', u'delay_16th_4', u'delay_16th_5', u'delay_16th_6', u'delay_16th_8', u'delay_16th_16'),
            u'R 16th': (u'delay_16th_1', u'delay_16th_2', u'delay_16th_3', u'delay_16th_4', u'delay_16th_5', u'delay_16th_6', u'delay_16th_8', u'delay_16th_16'),
            u'Channel': (u'utility_stereo', u'utility_left', u'utility_right'),
            u'Link Switch': (u'utility_stereo', u'utility_left'),
            u'L Sync Enum': SYNC,
            u'R Sync Enum': SYNC,
            u'Ping Pong': ACTIVATE},
 u'DrumBuss': {u'Drive Type': (u'drumbuss_soft', u'drumbuss_medium', u'drumbuss_hard')},
 u'Tube': {u'Tube Type': (u'tube_a', u'tube_b', u'tube_c')},
 u'Echo': {u'L Sync Mode': (u'echo_note', u'echo_triplet', u'echo_dotted', u'echo_16th'),
           u'R Sync Mode': (u'echo_note', u'echo_triplet', u'echo_dotted', u'echo_16th'),
           u'Mod Wave': (u'lfo_sine_small', u'lfo_triangle_small', u'lfo_saw_up_small', u'lfo_saw_down_small', u'lfo_square_small', u'lfo_random_small'),
           u'Link': ACTIVATE,
           u'Ping Pong': ACTIVATE,
           u'Repitch': ACTIVATE,
           u'Filter On': ACTIVATE,
           u'Mod Sync': ACTIVATE},
 u'Eq8': {u'Band': (u'eq8_band1', u'eq8_band2', u'eq8_band3', u'eq8_band4', u'eq8_band5', u'eq8_band6', u'eq8_band7', u'eq8_band8'),
          u'1 Filter Type A': EQ8_FILTER_TYPES,
          u'2 Filter Type A': EQ8_FILTER_TYPES,
          u'3 Filter Type A': EQ8_FILTER_TYPES,
          u'4 Filter Type A': EQ8_FILTER_TYPES,
          u'5 Filter Type A': EQ8_FILTER_TYPES,
          u'6 Filter Type A': EQ8_FILTER_TYPES,
          u'7 Filter Type A': EQ8_FILTER_TYPES,
          u'8 Filter Type A': EQ8_FILTER_TYPES,
          u'1 Filter On A': ACTIVATE,
          u'2 Filter On A': ACTIVATE,
          u'3 Filter On A': ACTIVATE,
          u'4 Filter On A': ACTIVATE,
          u'5 Filter On A': ACTIVATE,
          u'6 Filter On A': ACTIVATE,
          u'7 Filter On A': ACTIVATE,
          u'8 Filter On A': ACTIVATE},
 u'FilterEQ3': {u'LowOn': ACTIVATE,
                u'MidOn': ACTIVATE,
                u'HighOn': ACTIVATE},
 u'FilterDelay': {u'1 Input On': ACTIVATE,
                  u'2 Input On': ACTIVATE,
                  u'3 Input On': ACTIVATE,
                  u'1 Delay Mode': ACTIVATE,
                  u'2 Delay Mode': ACTIVATE,
                  u'3 Delay Mode': ACTIVATE},
 u'FrequencyShifter': {u'Wide': ACTIVATE,
                       u'Drive On/Off': ACTIVATE},
 u'GlueCompressor': {u'Peak Clip In': ACTIVATE},
 u'GrainDelay': {u'Delay Mode': ACTIVATE},
 u'Hybrid': {u'Section': (u'hybrid_reverb_section_convolution', u'hybrid_reverb_section_algo', u'hybrid_reverb_section_mix', u'hybrid_reverb_section_eq'),
             u'Algo Type': (u'hybrid_reverb_type_darkhall', u'hybrid_reverb_type_quartz', u'hybrid_reverb_type_shimmer', u'hybrid_reverb_type_tides', u'hybrid_reverb_type_prism'),
             u'Vintage Copy': (u'hybrid_reverb_vintage_1', u'hybrid_reverb_vintage_2', u'hybrid_reverb_vintage_3', u'hybrid_reverb_vintage_4', u'hybrid_reverb_vintage_5'),
             u'Routing Eq Off': (u'hybrid_reverb_routing_serial', u'hybrid_reverb_routing_parallel', u'hybrid_reverb_routing_algo', u'hybrid_reverb_routing_convo'),
             u'Routing Eq On PreAlgo Off': (u'hybrid_reverb_routing_serial_eq', u'hybrid_reverb_routing_parallel_eq', u'hybrid_reverb_routing_algo_eq', u'hybrid_reverb_routing_convo_eq'),
             u'Routing Eq On PreAlgo On': (u'hybrid_reverb_routing_serial_eq_pre_algo', u'hybrid_reverb_routing_parallel_eq_pre_algo', u'hybrid_reverb_routing_algo_eq_pre_algo', u'hybrid_reverb_routing_convo_eq_pre_algo')},
 u'InstrumentVector': {u'Oscillator': WAVETABLE_OSCILLATOR_SWITCH,
                       u'Osc 1 Effect Type': WAVETABLE_OSCILLATOR_EFFECT_TYPES,
                       u'Osc 2 Effect Type': WAVETABLE_OSCILLATOR_EFFECT_TYPES,
                       u'Sub Transpose': (u'wavetable_octave_0', u'wavetable_octave_minus_1', u'wavetable_octave_minus_2'),
                       u'Filter': (u'wavetable_filter_switch_1', u'wavetable_filter_switch_2'),
                       u'Filter 1 Type': WAVETABLE_FILTER_TYPES,
                       u'Filter 2 Type': WAVETABLE_FILTER_TYPES,
                       u'Filter 1 On': ACTIVATE,
                       u'Filter 2 On': ACTIVATE,
                       u'Filter 1 LP/HP': FILTER_CIRCUIT_TYPES,
                       u'Filter 2 LP/HP': FILTER_CIRCUIT_TYPES,
                       u'Filter 1 BP/NO/Morph': FILTER_CIRCUIT_TYPES,
                       u'Filter 2 BP/NO/Morph': FILTER_CIRCUIT_TYPES,
                       u'Filter Routing': (u'wavetable_routing_serial', u'wavetable_routing_parallel', u'wavetable_routing_split'),
                       u'Amp Env View': (u'wavetable_env_time', u'wavetable_env_slope'),
                       u'Mod Env View': (u'wavetable_env_time', u'wavetable_env_slope', u'wavetable_env_value'),
                       u'Amp Loop Mode': WAVETABLE_LOOP_MODE,
                       u'Env 2 Loop Mode': WAVETABLE_LOOP_MODE,
                       u'Env 3 Loop Mode': WAVETABLE_LOOP_MODE,
                       u'LFO 1 Shape': WAVETABLE_LFO_TYPES,
                       u'LFO 2 Shape': WAVETABLE_LFO_TYPES,
                       u'LFO 1 Retrigger': ACTIVATE,
                       u'LFO 2 Retrigger': ACTIVATE,
                       u'Mono On': ACTIVATE,
                       u'Unison Mode': (u'wavetable_unison_none', u'wavetable_unison_classic', u'wavetable_unison_shimmer', u'wavetable_unison_noise', u'wavetable_unison_phase_sync', u'wavetable_unison_position_spread', u'wavetable_unison_random'),
                       u'Unison Voices': WAVETABLE_VOICES,
                       u'Poly Voices': WAVETABLE_VOICES},
 u'Limiter': {u'Auto': ACTIVATE,
              u'Link Channels': ACTIVATE},
 u'Looper': {u'Reverse': ACTIVATE},
 u'MultibandDynamics': {u'Band Activator (Low)': ACTIVATE,
                        u'Band Activator (Mid)': ACTIVATE,
                        u'Band Activator (High)': ACTIVATE,
                        u'Soft Knee On/Off': ACTIVATE},
 u'Pedal': {u'Type': (u'pedal_overdrive', u'pedal_distortion', u'pedal_fuzz'),
            u'Sub': ACTIVATE},
 u'Redux': {u'Bit On': ACTIVATE},
 u'Redux2': {u'DC Shift': ACTIVATE,
             u'Pre-Filter On': ACTIVATE},
 u'Resonator': {u'Const': ACTIVATE,
                u'Filter On': ACTIVATE,
                u'I On': ACTIVATE,
                u'II On': ACTIVATE,
                u'III On': ACTIVATE,
                u'IV On': ACTIVATE,
                u'V On': ACTIVATE},
 u'Reverb': {u'In LowCut On': ACTIVATE,
             u'In HighCut On': ACTIVATE,
             u'ER Spin On': ACTIVATE,
             u'HiShelf On': ACTIVATE,
             u'LowShelf On': ACTIVATE,
             u'Freeze On': ACTIVATE,
             u'Flat On': ACTIVATE,
             u'Cut On': ACTIVATE,
             u'Chorus On': ACTIVATE},
 u'Saturator': {u'Color': ACTIVATE,
                u'Soft Clip': ACTIVATE},
 u'StereoGain': {u'Mute': ACTIVATE,
                 u'BlockDc': ACTIVATE,
                 u'Channel Mode': (u'utility_left', u'utility_stereo', u'utility_right', u'utility_swap'),
                 u'Left Inv': ACTIVATE,
                 u'Right Inv': ACTIVATE},
 u'Transmute': {u'Mod Mode': (u'transmute_mod_mode_none', u'transmute_mod_mode_chorus', u'transmute_mod_mode_wander', u'transmute_mod_mode_granular')},
 u'Spectral': {u'Mode': (u'spectraltime_manual', u'spectraltime_retrigger'),
               u'On': ACTIVATE,
               u'Delay On': ACTIVATE},
 u'Vinyl': {u'Tracing On': ACTIVATE,
            u'Pinch On': ACTIVATE},
 u'Vocoder': {u'Precise/Retro': ACTIVATE,
              u'Enhance': ACTIVATE},
 u'MidiArpeggiator': {u'Hold On': ACTIVATE,
                      u'Sync On': ACTIVATE,
                      u'Velocity On': ACTIVATE,
                      u'Vel. Retrigger': ACTIVATE},
 u'MidiNoteLength': {u'Trigger Mode': ACTIVATE,
                     u'Sync On': ACTIVATE},
 u'MidiRandom': {u'Mode': ACTIVATE},
 u'MidiScale': {u'Fold': ACTIVATE}}

def get_image_filenames_from_ids(image_ids, small_images = False, image_id_to_filename = IMAGE_ID_TO_FILENAME):
    image_index = 1 if small_images else 0
    return [ image_id_to_filename.get(image_id, (u'', u''))[image_index] for image_id in image_ids ]


def get_image_filenames(parameter_name, device_type, small_images = False, device_parameter_images = DEVICE_PARAMETER_IMAGES, generic_parameter_images = GENERIC_PARAMETER_IMAGES, image_id_to_filename = IMAGE_ID_TO_FILENAME):
    image_ids = []
    if device_type in device_parameter_images and parameter_name in device_parameter_images[device_type]:
        image_ids = device_parameter_images[device_type][parameter_name]
    elif parameter_name in generic_parameter_images:
        image_ids = generic_parameter_images[parameter_name]
    return get_image_filenames_from_ids(image_ids, small_images=small_images, image_id_to_filename=image_id_to_filename)
